/*
 * This source file was generated by the Gradle 'init' task
 */

//I will be building for one physical vending machine
// Multiple people can browse the items through a web interface concurrently.
// If payment is online, then dispensing will be separated from payment, and dispensing will be controlled with a payment completed code.
// If it is cash, dispensing will be sequential, right after payment. And dispensing will always be sequential for customers, serving only one at a time.
package org.vending_machine;

import org.example.list.LinkedList;

import static org.example.utilities.StringUtils.join;
import static org.example.utilities.StringUtils.split;
import static org.example.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class VendingMachine {
    public static void main(String[] args) {
    }
}
