/*
 * This source file was generated by the Gradle 'init' task
 */
package org.parking_lot;

public class ParkingLot {

    public static void main(String[] args) {
        System.out.println("Main thread: " + Thread.currentThread().getName());
    }
}
